name: lm_labs_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1000000

environment:
  flutter: ">=3.29.0"
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.8.0
  hooks_riverpod: ^2.6.1
  i18n_extension: ^15.0.4
  json_annotation: ^4.9.0
  lm_labs_utils: ^1.1.3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  # flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  go_router_builder: ^2.8.0
  json_serializable: ^6.9.4
  lm_labs_flutter_lints: ^0.3.0
  lm_labs_generator: ^0.0.2
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/flutter_logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/flutter_logo.png
  info_plist_files:
    - "ios/Runner/Info.plist"
